### ISSUE TITLE
CASEVAC chopper using a 9 liners.

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [MisterHLunaticwraith/MRHMilsimTools#15]
Suggestion by alexGardien
Add a medevac module, so squad leader can call in a CASEVAC chopper using a 9 liners. Inspired from the RMM CASEVAC script from Arma 2 MSO. You had to fill the form and https://github.com/MisterHLunaticwraith/MRHMilsimTools/issues/newthen the helicopter would come after X time.

Note : Sorry if i'am not at the correct place to post suggestions I don't really know how to use this website haha !

**Comment by kennychr** [comment]
Hey! I had already made something similar to the A2 MSO script in A3 a while back, heavily influence by the RMM script. You can use it if you want it. Just tell me if you want the link!

**Comment by MisterHLunaticwraith** [comment]
Thanks, I usually prefer writing my own scripts so I don't have to reverse engineer whatever other people have made! It can't hurt to have a look though. My intention is to do a simplified CASEVAC script where the helo will fly away, heal all onboard and bring them back.

**Comment by kennychr** [comment]
Its built into this: https://github.com/kennychr/ch_framework 

Just note that i made that casevac script about 2 years ago and i got it to work-ish but if it can give you ideas go ahead!

**Comment by MisterHLunaticwraith** [comment]
Added in v1.17.4
