### ISSUE TITLE
HeliTaxi

### ISSUE THREAD

**Issue by Burbonizer** [MisterHLunaticwraith/MRHMilsimTools#18]
Sorry another request rather than a error.....

I was wondering if you could change the code to give the player who commanded the heli to take off via a action or interaction. 

I have found that i have to AI to disembark before touching down in order to get them out. If you try after it has landed and you have already been kicked out of the heli, they reply with negative and the heli takes off with them still in.

Another scenario would be that you call the heli, you have yourself and a AI squad plus one more player who is a sniper. You set a LZ of one location (waypoint) and the final LZ on a hill for the sniper. So you land and get out. Tell your Ai to get out and then interact with the heli to continue to next WP (or return to base). That way everyone would get dropped off where they wanted and the player has full control of the heli.

Been looking for a good helitaxi script for ages and so far this works really well apart from the landing part.

**Comment by MisterHLunaticwraith** [comment]
I can easily implement your first request (i never play along with AIs so I didn't even think about it) the second is a tad more complicated, I'll look into it.

**Comment by Burbonizer** [comment]
Brilliant. I think if you gave the option for the action or interaction (with ace) for the player to dismiss the heli on landing, then it may work very well. That would give the player the ability to ensure everyone is off and it is ok to proceed. But saying that if it was'nt and the player wished to go elsewhere, then they couldnt anyway without dismissing it and calling a new one. If you are doing this, what about utilising the script you have written to call the heli and on the action or interaction, you can request them to power down engines (more tricky i know). That way you can come back to the heli and then move on. I am sorry, i am not writing the code but these ideas just keep coming to me lol.

My second suggestion was a little more in depth i agree. Not sure how many people would use it, but would be nice.

**Comment by MisterHLunaticwraith** [comment]
Most of what you asked is now present in v1.17.4
