### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by c0nnex** [MisterHLunaticwraith/MRHMilsimTools#20]
Great toolset!
Using only HeliTaxi (which depends on MRHEnhandcedMap and MRHMarkers unfortunately,else it throws errors) for now on my KP Liberation Server, but will look into the rest as well.

Suggestions:
General
- Do not add the CBA Settings for not loaded pbo's in the CoreModule. This is very confusing, if you only use a subset and have options for not loaded stuff. Instead have every module propagate it's settings itself (or at least check if the pbo is loaded eg CAS). Else you do not need diffrent pbo if everything is hardwired in the core anyway and they depend on each other.

HeliTaxi
- Add an option to the HeliTaxi to select the flight height
- Add an option to the HeliTaxi to "Hover at Destination" instead of landing and throwing the passengers out, so you can rappel etc.
- Add an option to HeliTaxi to "Stay at LZ (Engine on)" , "Stay at LZ (Engine off)" so you can comeback later jump in again and fly on, instead of calling a new taxi. eg. if you just want to pick someone up or grab a quick intel (aLive has this and it's a great feature imho). 
- Add a possibility to the set the HomeBase of the Heli instead of a random point. E.g.: if there is a Marker "MRHHeliTaxi_Base" then it will start and end there.
- Add an Ace3-Command "Return to Base". (useful for the hover and stay options ;) )

(can help with implementations if needed/wanted)

In case you want it here's the errors when using HeliTaxi without MRHMarkers and MRHEnhancedMap:
`
The HeliTaxi works basically, but when the "Select Destination" Map is opened following errors occur (Error Box):
Error in expression <
openMap [true,true];
[] spawn MRH_fnc_MilsimTools_EnhancedMap_temporar>
20:59:05   Error position: <MRH_fnc_MilsimTools_EnhancedMap_temporar>
20:59:05   Error Nicht definierte Variable in Ausdruck: mrh_fnc_milsimtools_enhancedmap_temporarymap
20:59:05 File \MRHHeliTaxi\Functions\fn_MilsimTools_HeliTaxi_HeliTaxiCall.sqf [MRH_fnc_MilsimTools_HeliTaxi_HeliTaxiCall], line 72
`
and then log is spammed with
`No entry 'bin\config.bin/CfgMarkers.MRH_Heli'`
`No entry 'bin\config.bin/CfgMarkers.MRH_waypoint'`
The taxi works, but you cannot see the route on the map which is really confusing when trying to set a route to the LZ, avoiding enemy sectors.

**Comment by MisterHLunaticwraith** [comment]
The module (as all modules in the mod) is not meant to function independently and that will not change sorry. Most of them call to functions in the core addon and sometimes to other addons. In short, if you do not want these errors, use the full mod!

As per your other suggestions they are all planned features, but I will probably only get back to working on the mod in August.
You can track the project her: https://github.com/MisterHLunaticwraith/MRHMilsimTools/projects/1
