### ISSUE TITLE
Heli Taxi Wont Take-off

### ISSUE THREAD

**Issue by MIkes285** [MisterHLunaticwraith/MRHMilsimTools#21]
**Arma 3 Version:** `1.92.145639` stable
**CBA Version:** `3.12.0` (stable / dev + commit hash)
**ACE3 Version:** `latestx` (stable / rc / dev)
**Milsim Tools Version:** `latest` (stable / rc / dev)

**Mods:**
```
-

ace 
ACE Compat - RHS Armed Forces of the Russian Federation | Steam | 
ACE Compat - RHS United States Armed Forces | Steam | 
Achilles 
ACRE2 
Advanced Rappelling
Advanced Sling Loading
Advanced Towing 
Advanced Urban Rappelling
Blastcore Edited (standalone version) | Steam | 
CBA_A3 
DynaSound 2 
Enhanced Movement 
Enhanced Soundscape
F-15 Eagle 
FA-18 Super Hornet
FIR AWS(AirWeaponSystem)
Immerse
MRHMilSimTools 
RHSAFRF 
RHSUSAF 
ShackTac 
Suppress


```

**Description:**
using kp liberation, only using heli taxi module, heli comes in, lands, but doen not take off to set destination, if we eject, the cancel taxi works fine

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated -  Editor (Multiplayer) 
NO SUPPORT FOR SP, please make sure that you are using the mod in MP even when testing in the editor.
NO SUPPORT FOR OUTDATED Version, 
please make sure that you are using latest version especially if you use a repacked version or armasync version.
Though repacking and redistributing this mod is allowed without asking for my explicit consent,
 I will offer support only for the original version distributed on the steam workshop.

**RPT log file:**

[arma3server_2019-07-12_13-41-03.zip](https://github.com/MisterHLunaticwraith/MRHMilsimTools/files/3386349/arma3server_2019-07-12_13-41-03.zip)

**Comment by MIkes285** [comment]
Update, when testing in editor as multiplayer on my local machine, it works perfectly, so seems to be a server issue?

**Comment by MisterHLunaticwraith** [comment]
Maybe, please make sure that the mod is correctly enabled on the server. Check the server rpt and link it here too (a pastebin link if you can would be better than a zip file.

**Comment by MIkes285** [comment]
is there something i can do to make sure it is enabled properly, the heli comes in and lands, just wont accept the new destination for the drop off, i get the message, en route to destination, but no radio, and the heli doesn't take off, 
i will do a clean liberation server with only that this mod running and see if it still does it.

**Comment by MisterHLunaticwraith** [comment]
There might also be a conflict with another mod. I'm away from home and won't be able to run tests for a while sorry.
